name: Docker-tdlib

on:
  workflow_dispatch:
    inputs:
      name:
        description: '备注'
        required: true
        default: '生成tdlib-alpine基础包'

  check_suite:
    types: [rerequested, completed]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: buildx-alpine
        run: |
          source ./VERSION
          docker buildx build --tag scjtqs/tdlib:${BUILD_VERSION}-alpine --platform linux/amd64,linux/arm64,linux/arm/v7 --build-arg BUILD_VERSION="${BUILD_VERSION}" --build-arg TD_GIT_COMMIT="${TD_GIT_COMMIT}" --push -f alpine.td.Dockerfile . || exit 2
