name: Docker-tdlib

on:
  workflow_dispatch:
    inputs:
      name:
        description: '备注'
        required: true
        default: '生成tdlib基础包'

  check_suite:
    types: [rerequested, completed]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: scjtqs/go-tg:test

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run tests
#        run: |
#          if [ -f docker-compose.test.yml ]; then
#            docker-compose --file docker-compose.test.yml build
#            docker-compose --file docker-compose.test.yml run sut
#          else
#            docker build . --file Dockerfile
#          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  bullseye:
    # Ensure test job passes before pushing image.
#    needs: test

    runs-on: ubuntu-latest
#    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

#      - name: Build image
#        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#      - name: Log into aliyun repo
#        run: echo "${{ secrets.DOCKER_PASSWORD2 }}" | docker login  -u ${{ secrets.DOCKER_USERNAME2 }} registry.cn-hangzhou.aliyuncs.com --password-stdin

#      - name: Push image
#        run: docker push $IMAGE_NAME
        
      - name: buildx-bullseye
        run: ./buildForTdlib-bullseye.sh
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  alpine:
    # Ensure test job passes before pushing image.
    #    needs: test

    runs-on: ubuntu-latest
    #    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      #      - name: Build image
      #        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login  -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        #      - name: Log into aliyun repo
        #        run: echo "${{ secrets.DOCKER_PASSWORD2 }}" | docker login  -u ${{ secrets.DOCKER_USERNAME2 }} registry.cn-hangzhou.aliyuncs.com --password-stdin

        #      - name: Push image
        #        run: docker push $IMAGE_NAME

      - name: buildx-alpine
        run: ./buildForTdlib-alpine.sh