name: Docker-base

on:
  workflow_dispatch:
    inputs:
      name:
        description: '备注'
        required: true
        default: '生成golang基础包'

  check_suite:
    types: [rerequested, completed]

env:
  IMAGE_NAME: scjtqs/go-tg:test

jobs:
  bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: buildx-bullseye
        run: docker buildx build --tag scjtqs/tdlib:bullseye-base --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7  --push -f bullseye.base.Dockerfile . || exit 2
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: buildx-alpine
        run: docker buildx build --tag scjtqs/tdlib:alpine-base --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7  --push -f alpine.base.Dockerfile .  || exit 2
